swagger: '2.0'
info:
  title: Pakkasmarja REST API
  description: REST API for Pakkasmarja
  version: 0.0.2
schemes:
  - https
basePath: /rest/v1
consumes:
  - application/json;charset=utf-8
produces:
  - application/json;charset=utf-8
paths:
  /contacts:
    get:
      operationId: listContacts
      summary: Lists contacts
      description: Lists contacts
      tags:
        - Contacts
      responses:
        '200':
          description: List of contacts
          schema:
            type: array
            items:
              $ref: '#/definitions/Contact'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/contacts/{id}':
    get:
      operationId: findContact
      summary: Find contact
      description: Finds contact by id
      tags:
        - Contacts
      parameters:
        - name: id
          required: true
          in: path
          description: contact id
          type: string
          format: uuid
      responses:
        '200':
          description: A contact
          schema:
            $ref: '#/definitions/Contact'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
    put:
      operationId: updateContact
      summary: Update contact
      description: Updates single contact
      tags:
        - Contacts
      parameters:
        - name: id
          required: true
          in: path
          description: contact id
          type: string
          format: uuid
        - name: body
          in: body
          description: Payload
          required: true
          schema:
            $ref: '#/definitions/Contact'
      responses:
        '200':
          description: Updated contact
          schema:
            $ref: '#/definitions/Contact'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /contracts:
    get:
      operationId: listContracts
      summary: Lists contracts
      description: Lists contracts
      tags:
        - Contracts
      responses:
        '200':
          description: List of contracts
          schema:
            type: array
            items:
              $ref: '#/definitions/Contract'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/contracts/{id}':
    get:
      operationId: findContract
      summary: Find contract
      description: Finds contract by id
      tags:
        - Contracts
      parameters:
        - name: id
          required: true
          in: path
          description: contract id
          type: string
          format: uuid
      responses:
        '200':
          description: A contract
          schema:
            $ref: '#/definitions/Contract'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
    put:
      operationId: updateContract
      summary: Update contract
      description: Updates single contract
      tags:
        - Contracts
      parameters:
        - name: id
          required: true
          in: path
          description: contract id
          type: string
          format: uuid
        - name: body
          in: body
          description: Payload
          required: true
          schema:
            $ref: '#/definitions/Contract'
      responses:
        '200':
          description: Updated contract
          schema:
            $ref: '#/definitions/Contract'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/contracts/{id}/documents/{type}':
    get:
      operationId: getContractDocument
      summary: Returns contract document
      description: Returns contract document by type
      tags:
        - Contracts
      parameters:
        - name: id
          required: true
          in: path
          description: contract id
          type: string
          format: uuid
        - name: type
          required: true
          in: path
          description: document type
          type: string
        - name: format
          required: true
          in: query
          description: document format (HTML or PDF)
          type: string
      responses:
        '200':
          description: Document data
          schema:
            type: string
            format: binary
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/contracts/{id}/documents/{type}/signRequests':
    post:
      operationId: createContractDocumentSignRequest
      summary: Requests contract document electronic signing
      description: Requests contract document electronic signing
      tags:
        - Contracts
      parameters:
        - name: id
          required: true
          in: path
          description: contract id
          type: string
          format: uuid
        - name: type
          required: true
          in: path
          description: document type
          type: string
        - name: body
          in: body
          description: Payload
          required: true
          schema:
            $ref: '#/definitions/ContractDocumentSignRequest'
      responses:
        '200':
          description: Contract document sign request with redirect url filled
          schema:
            $ref: '#/definitions/ContractDocumentSignRequest'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /itemGroups:
    get:
      operationId: listItemGroups
      summary: Lists itemGroups
      description: Lists itemGroups
      tags:
        - ItemGroups
      responses:
        '200':
          description: List of item groups
          schema:
            type: array
            items:
              $ref: '#/definitions/ItemGroup'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/itemGroups/{id}':
    get:
      operationId: findItemGroup
      summary: Find item group
      description: Finds item group by id
      tags:
        - ItemGroups
      parameters:
        - name: id
          required: true
          in: path
          description: item group id
          type: string
          format: uuid
      responses:
        '200':
          description: A item group
          schema:
            $ref: '#/definitions/ItemGroup'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/operations':
    post:
      operationId: createOperation
      summary: Creates new operation
      description: Creates new operation
      tags:
        - Operations
      parameters:
        - name: body
          in: body
          description: Payload
          required: true
          schema:
            $ref: '#/definitions/Operation'
      responses:
        '200':
          description: Operation created successful
          schema:
            $ref: '#/definitions/Operation'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/operationReports':
    get:
      operationId: listOperationReports
      summary: List operation reports
      description: Lists operation reports
      tags:
        - OperationReports
      parameters:
        - name: type
          in: query
          description: filter by type
          type: string
        - name: sortBy
          in: query
          description: sort by (CREATED)
          type: string
        - name: sortDir
          in: query
          description: sort direction (ASC, DESC)
          type: string
        - name: firstResult
          in: query
          description: Offset of first result. Defaults to 0
          type: integer
          format: int64
        - name: maxResults
          in: query
          description: Max results. Defaults to 20
          type: integer
          format: int64
      responses:
        '200':
          description: List of operation reports
          schema:
            type: array
            items:
              $ref: '#/definitions/OperationReport'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/operationReports/{id}':
    get:
      operationId: findOperationReport
      summary: Find operation report
      description: Find operation report by id
      tags:
        - OperationReports
      parameters:
        - name: id
          required: true
          in: path
          description: operation report id
          type: string
          format: uuid
      responses:
        '200':
          description: A operation report
          schema:
            $ref: '#/definitions/OperationReport'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  '/operationReports/{id}/items':
    get:
      operationId: listOperationReportItems
      summary: List operation report items
      description: Lists operation report items
      tags:
        - OperationReports
      parameters:
        - name: id
          required: true
          in: path
          description: operation report id
          type: string
          format: uuid
      responses:
        '200':
          description: A list of operation report items
          schema:
            $ref: '#/definitions/OperationReportItem'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
definitions:
  Contact:
    type: object
    properties:
      id:
        type: string
        format: uuid
      firstName:
        type: string
      lastName:
        type: string
      companyName:
        type: string
      phoneNumbers:
        type: array
        items:
          type: string
      email:
        type: string
        format: email
      addresses:
        type: array
        items:
          $ref: '#/definitions/Address'
      BIC:
        type: string
      IBAN:
        type: string
      taxCode:
        type: string
      vatLiable:
        type: string
        enum:
          - 'YES'
          - 'NO'
          - EU
      audit:
        type: string
  Contract:
    type: object
    properties:
      id:
        type: string
        format: uuid
      itemGroupId:
        type: string
        format: uuid
      quantity:
        type: number
        format: double
      delivered:
        type: number
        format: double
      startDate:
        type: string
        format: date
      endDate:
        type: string
        format: date
      signDate:
        type: string
        format: date
      termDate:
        type: string
        format: date
      status:
        type: string
        enum:
          - APPROVED
          - ON_HOLD
          - DRAFT
          - TERMINATED
      remarks:
        type: string
  ContractDocumentSignRequest:
    type: object
    properties:
      redirectUrl:
        type: string
  ItemGroup:
    type: object
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
  Address:
    type: object
    properties:
      type:
        type: string
      streetAddress:
        type: string
      postalCode:
        type: string
      city:
        type: string
  Operation:
    type: object
    properties:
      type:
        type: string
      operationReportId:
        type: string
        format: uuid
  OperationReport:
    type: object
    properties:
      id:
        type: string
        format: uuid
      type:
        type: string
      started:
        type: string
        format: date-time
      pendingCount:
        type: integer
        format: int32
      failedCount:
        type: integer
        format: int32
      successCount:
        type: integer
        format: int32  
  OperationReportItem:
    type: object
    properties:
      status:
        type: string
        enum:
          - PENDING
          - FAILURE
          - SUCCESS
      message:
        type: string
  InternalServerError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  Forbidden:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  BadRequest:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  NotImplemented:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  NotFound:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
