swagger: '2.0'
info:
  title: Pakkasmarja REST API
  description: REST API for Pakkasmarja
  version: 0.0.1
schemes:
  - https
basePath: /rest/v1
consumes:
  - application/json;charset=utf-8
produces:
  - application/json;charset=utf-8
paths:
  /contacts:
    get:
      operationId: listContacts
      summary: Lists contacts
      description: Lists contacts
      tags:
        - Contacts
      responses:
        '200':
          description: List of contacts
          schema:
            type: array
            items:
              $ref: '#/definitions/Contact'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /contacts/{id}:
    get:
      operationId: findContact
      summary: Find contact
      description: Finds contact by id
      tags:
        - Contacts
      parameters: 
        - name: id
          required: true
          in: path
          description: contact id
          type: string
          format: uuid
      responses:
        '200':
          description: A contact
          schema:
            $ref: '#/definitions/Contact'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
    put:
      operationId: updateContact
      summary: Update contact
      description: Updates single contact
      tags:
        - Contacts
      parameters: 
        - name: id
          required: true
          in: path
          description: contact id
          type: string
          format: uuid
        - name: body
          in: body
          description: Payload
          required: true
          schema:
            $ref: '#/definitions/Contact'
      responses:
        '200':
          description: Updated contact
          schema:
            $ref: '#/definitions/Contact'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /contracts:
    get:
      operationId: listContracts
      summary: Lists contracts
      description: Lists contracts
      tags:
        - Contracts
      responses:
        '200':
          description: List of contracts
          schema:
            type: array
            items:
              $ref: '#/definitions/Contract'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /contracts/{id}:
    get:
      operationId: findContract
      summary: Find contract
      description: Finds contract by id
      tags:
        - Contracts
      parameters: 
        - name: id
          required: true
          in: path
          description: contract id
          type: string
          format: uuid
      responses:
        '200':
          description: A contract
          schema:
            $ref: '#/definitions/Contract'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
    put:
      operationId: updateContract
      summary: Update contract
      description: Updates single contract
      tags:
        - Contracts
      parameters: 
        - name: id
          required: true
          in: path
          description: contract id
          type: string
          format: uuid
        - name: body
          in: body
          description: Payload
          required: true
          schema:
            $ref: '#/definitions/Contract'
      responses:
        '200':
          description: Updated contract
          schema:
            $ref: '#/definitions/Contract'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /itemGroups:
    get:
      operationId: listItemGroups
      summary: Lists itemGroups
      description: Lists itemGroups
      tags:
        - ItemGroups
      responses:
        '200':
          description: List of item groups
          schema:
            type: array
            items:
              $ref: '#/definitions/ItemGroup'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /itemGroups/{id}:
    get:
      operationId: findItemGroup
      summary: Find item group
      description: Finds item group by id
      tags:
        - ItemGroups
      parameters: 
        - name: id
          required: true
          in: path
          description: item group id
          type: string
          format: uuid
      responses:
        '200':
          description: A item group
          schema:
            $ref: '#/definitions/ItemGroup'
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /system/shutdown:
    post:
      operationId: systemShutdown
      summary: Shutdown system
      description: Shuts the system down
      tags:
        - System
      responses:
        '204':
          description: Ok
        '400':
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        '403':
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
definitions:
  Contact:
    type: object
    properties:
      id:
        type: string
        format: uuid
      sapId:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      companyName:
        type: string
      phoneNumbers:
        type: array
        items:
          type: string
      email:
        type: string
        format: email
      addresses:
        type: array
        items:
          $ref: '#/definitions/Address'
      BIC:
        type: string
      IBAN:
        type: string
      taxCode:
        type: string
      vatLiable:
        type: string
        enum:
          - YES
          - NO
          - EU
      audit:
        type: string
  Contract:
    type: object
    properties:
      id:
        type: string
        format: uuid
      itemGroupId:
        type: string
        format: uuid
      quantity:
        type: integer
        format: int64
      startDate:
        type: string
        format: date
      endDate:
        type: string
        format: date
      signDate:
        type: string
        format: date
      termDate:
        type: string
        format: date
      status:
        type: string
        enum: [APPROVED, ON_HOLD, DRAFT, TERMINATED]
      remarks:
        type: string
  ItemGroup:
    type: object
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
  Address:
    type: object
    properties:
      id:
        type: integer
        format: int64
      type: 
        type: string
      streetAddress:
        type: string
      postalCode:
        type: string
      city:
        type: string
  InternalServerError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  Forbidden:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  BadRequest:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  NotImplemented:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  NotFound:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
