/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 0.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PakkasmarjaRestClient);
  }
}(this, function(expect, PakkasmarjaRestClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PakkasmarjaRestClient.ChatThread();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChatThread', function() {
    it('should create an instance of ChatThread', function() {
      // uncomment below and update the code to test ChatThread
      //var instane = new PakkasmarjaRestClient.ChatThread();
      //expect(instance).to.be.a(PakkasmarjaRestClient.ChatThread);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new PakkasmarjaRestClient.ChatThread();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new PakkasmarjaRestClient.ChatThread();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new PakkasmarjaRestClient.ChatThread();
      //expect(instance).to.be();
    });

    it('should have the property originId (base name: "originId")', function() {
      // uncomment below and update the code to test the property originId
      //var instane = new PakkasmarjaRestClient.ChatThread();
      //expect(instance).to.be();
    });

    it('should have the property imageUrl (base name: "imageUrl")', function() {
      // uncomment below and update the code to test the property imageUrl
      //var instane = new PakkasmarjaRestClient.ChatThread();
      //expect(instance).to.be();
    });

    it('should have the property answerType (base name: "answerType")', function() {
      // uncomment below and update the code to test the property answerType
      //var instane = new PakkasmarjaRestClient.ChatThread();
      //expect(instance).to.be();
    });

  });

}));
