/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 0.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SoteapiClient);
  }
}(this, function(expect, SoteapiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SoteapiClient.Contract();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Contract', function() {
    it('should create an instance of Contract', function() {
      // uncomment below and update the code to test Contract
      //var instane = new SoteapiClient.Contract();
      //expect(instance).to.be.a(SoteapiClient.Contract);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SoteapiClient.Contract();
      //expect(instance).to.be();
    });

    it('should have the property contactId (base name: "contactId")', function() {
      // uncomment below and update the code to test the property contactId
      //var instane = new SoteapiClient.Contract();
      //expect(instance).to.be();
    });

    it('should have the property itemGroupId (base name: "itemGroupId")', function() {
      // uncomment below and update the code to test the property itemGroupId
      //var instane = new SoteapiClient.Contract();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instane = new SoteapiClient.Contract();
      //expect(instance).to.be();
    });

    it('should have the property delivered (base name: "delivered")', function() {
      // uncomment below and update the code to test the property delivered
      //var instane = new SoteapiClient.Contract();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "startDate")', function() {
      // uncomment below and update the code to test the property startDate
      //var instane = new SoteapiClient.Contract();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "endDate")', function() {
      // uncomment below and update the code to test the property endDate
      //var instane = new SoteapiClient.Contract();
      //expect(instance).to.be();
    });

    it('should have the property signDate (base name: "signDate")', function() {
      // uncomment below and update the code to test the property signDate
      //var instane = new SoteapiClient.Contract();
      //expect(instance).to.be();
    });

    it('should have the property termDate (base name: "termDate")', function() {
      // uncomment below and update the code to test the property termDate
      //var instane = new SoteapiClient.Contract();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new SoteapiClient.Contract();
      //expect(instance).to.be();
    });

    it('should have the property remarks (base name: "remarks")', function() {
      // uncomment below and update the code to test the property remarks
      //var instane = new SoteapiClient.Contract();
      //expect(instance).to.be();
    });

  });

}));
