/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 0.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SoteapiClient);
  }
}(this, function(expect, SoteapiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SoteapiClient.Contact();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Contact', function() {
    it('should create an instance of Contact', function() {
      // uncomment below and update the code to test Contact
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be.a(SoteapiClient.Contact);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "companyName")', function() {
      // uncomment below and update the code to test the property companyName
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumbers (base name: "phoneNumbers")', function() {
      // uncomment below and update the code to test the property phoneNumbers
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property addresses (base name: "addresses")', function() {
      // uncomment below and update the code to test the property addresses
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property BIC (base name: "BIC")', function() {
      // uncomment below and update the code to test the property BIC
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property IBAN (base name: "IBAN")', function() {
      // uncomment below and update the code to test the property IBAN
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property taxCode (base name: "taxCode")', function() {
      // uncomment below and update the code to test the property taxCode
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property vatLiable (base name: "vatLiable")', function() {
      // uncomment below and update the code to test the property vatLiable
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property audit (base name: "audit")', function() {
      // uncomment below and update the code to test the property audit
      //var instane = new SoteapiClient.Contact();
      //expect(instance).to.be();
    });

  });

}));
