/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ChatMessage { 
    id?: number;
    threadId: number;
    userId?: string;
    contents: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export interface ChatMessageOpt { 
    id?: number;
    threadId?: number;
    userId?: string;
    contents?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
