/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatGroupPermissionScope } from './chatGroupPermissionScope';


export interface ChatGroupGroupPermission { 
    readonly id?: string;
    chatGroupId: number;
    userGroupId: string;
    scope?: ChatGroupPermissionScope;
}
export interface ChatGroupGroupPermissionOpt { 
    readonly id?: string;
    chatGroupId?: number;
    userGroupId?: string;
    scope?: ChatGroupPermissionScope;
}
