/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ContractDocumentTemplate { 
    id?: string;
    contractId?: string;
    type: string;
    contents: string;
    header?: string;
    footer?: string;
}
export interface ContractDocumentTemplateOpt { 
    id?: string;
    contractId?: string;
    type?: string;
    contents?: string;
    header?: string;
    footer?: string;
}
