/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ContractStatus = 'APPROVED' | 'ON_HOLD' | 'DRAFT' | 'TERMINATED' | 'REJECTED';

export const ContractStatus = {
    APPROVED: 'APPROVED' as ContractStatus,
    ONHOLD: 'ON_HOLD' as ContractStatus,
    DRAFT: 'DRAFT' as ContractStatus,
    TERMINATED: 'TERMINATED' as ContractStatus,
    REJECTED: 'REJECTED' as ContractStatus
};
