/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AreaDetail } from './areaDetail';


export interface Contract { 
    id?: string;
    sapId?: string;
    contactId?: string;
    deliveryPlaceId?: string;
    proposedDeliveryPlaceId?: string;
    deliveryPlaceComment?: string;
    itemGroupId?: string;
    year: number;
    contractQuantity?: number;
    deliveredQuantity?: number;
    proposedQuantity?: number;
    quantityComment?: string;
    startDate?: string;
    endDate?: string;
    signDate?: string;
    termDate?: string;
    rejectComment?: string;
    areaDetails?: Array<AreaDetail>;
    deliverAll: boolean;
    status: Contract.StatusEnum;
    remarks?: string;
}
export interface ContractOpt { 
    id?: string;
    sapId?: string;
    contactId?: string;
    deliveryPlaceId?: string;
    proposedDeliveryPlaceId?: string;
    deliveryPlaceComment?: string;
    itemGroupId?: string;
    year?: number;
    contractQuantity?: number;
    deliveredQuantity?: number;
    proposedQuantity?: number;
    quantityComment?: string;
    startDate?: string;
    endDate?: string;
    signDate?: string;
    termDate?: string;
    rejectComment?: string;
    areaDetails?: Array<AreaDetail>;
    deliverAll?: boolean;
    status?: Contract.StatusEnum;
    remarks?: string;
}
export namespace Contract {
    export type StatusEnum = 'APPROVED' | 'ON_HOLD' | 'DRAFT' | 'TERMINATED' | 'REJECTED';
    export const StatusEnum = {
        APPROVED: 'APPROVED' as StatusEnum,
        ONHOLD: 'ON_HOLD' as StatusEnum,
        DRAFT: 'DRAFT' as StatusEnum,
        TERMINATED: 'TERMINATED' as StatusEnum,
        REJECTED: 'REJECTED' as StatusEnum
    };
}
