/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type DeliveryStatus = 'PROPOSAL' | 'PLANNED' | 'DELIVERY' | 'DONE' | 'REJECTED' | 'NOT_ACCEPTED';

export const DeliveryStatus = {
    PROPOSAL: 'PROPOSAL' as DeliveryStatus,
    PLANNED: 'PLANNED' as DeliveryStatus,
    DELIVERY: 'DELIVERY' as DeliveryStatus,
    DONE: 'DONE' as DeliveryStatus,
    REJECTED: 'REJECTED' as DeliveryStatus,
    NOTACCEPTED: 'NOT_ACCEPTED' as DeliveryStatus
};
