/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type DeliveryLoanItem = 'GRAY_BOX' | 'RED_BOX' | 'ORANGE_BOX' | 'GREEN_BOX';

export const DeliveryLoanItem = {
    GRAYBOX: 'GRAY_BOX' as DeliveryLoanItem,
    REDBOX: 'RED_BOX' as DeliveryLoanItem,
    ORANGEBOX: 'ORANGE_BOX' as DeliveryLoanItem,
    GREENBOX: 'GREEN_BOX' as DeliveryLoanItem
};
