/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeliveryQuality } from './deliveryQuality';
import { DeliveryStatus } from './deliveryStatus';


export interface Delivery { 
    id?: string;
    productId?: string;
    time?: string;
    status?: DeliveryStatus;
    amount?: number;
    price?: string;
    quality?: DeliveryQuality;
    deliveryPlaceId?: string;
}
export interface DeliveryOpt { 
    id?: string;
    productId?: string;
    time?: string;
    status?: DeliveryStatus;
    amount?: number;
    price?: string;
    quality?: DeliveryQuality;
    deliveryPlaceId?: string;
}
