/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ItemGroupDocumentTemplate { 
    id?: string;
    itemGroupId?: string;
    type?: string;
    contents: string;
    header?: string;
    footer?: string;
}
export interface ItemGroupDocumentTemplateOpt { 
    id?: string;
    itemGroupId?: string;
    type?: string;
    contents?: string;
    header?: string;
    footer?: string;
}
