/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NewsArticle { 
    id?: number;
    title: string;
    contents: string;
    imageUrl?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
export interface NewsArticleOpt { 
    id?: number;
    title?: string;
    contents?: string;
    imageUrl?: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}
