/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OpeningHourInterval { 
    id?: string;
    opens: Date;
    closes: Date;
}
export interface OpeningHourIntervalOpt { 
    id?: string;
    opens?: Date;
    closes?: Date;
}
