/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type OperationType = 'SAP_CONTACT_SYNC' | 'ITEM_GROUP_DEFAULT_DOCUMENT_TEMPLATES';

export const OperationType = {
    SAPCONTACTSYNC: 'SAP_CONTACT_SYNC' as OperationType,
    ITEMGROUPDEFAULTDOCUMENTTEMPLATES: 'ITEM_GROUP_DEFAULT_DOCUMENT_TEMPLATES' as OperationType
};
