/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OperationReportItem { 
    status?: OperationReportItem.StatusEnum;
    message?: string;
}
export interface OperationReportItemOpt { 
    status?: OperationReportItem.StatusEnum;
    message?: string;
}
export namespace OperationReportItem {
    export type StatusEnum = 'PENDING' | 'FAILURE' | 'SUCCESS';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        FAILURE: 'FAILURE' as StatusEnum,
        SUCCESS: 'SUCCESS' as StatusEnum
    };
}
