/**
 * Pakkasmarja REST API
 * REST API for Pakkasmarja
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type WeekdayType = 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY';

export const WeekdayType = {
    MONDAY: 'MONDAY' as WeekdayType,
    TUESDAY: 'TUESDAY' as WeekdayType,
    WEDNESDAY: 'WEDNESDAY' as WeekdayType,
    THURSDAY: 'THURSDAY' as WeekdayType,
    FRIDAY: 'FRIDAY' as WeekdayType,
    SATURDAY: 'SATURDAY' as WeekdayType,
    SUNDAY: 'SUNDAY' as WeekdayType
};
